
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NARESH
 */
public class choose_theatre extends javax.swing.JFrame {

    /**
     * Creates new form choose_theatre
     */
    public choose_theatre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pvr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        inox = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cinepolis = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datebox = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pvr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pvr.setForeground(new java.awt.Color(255, 255, 255));
        pvr.setText("PVR:velocity,vellore.");
        jPanel1.add(pvr, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 144, 239, 37));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("cancellation available");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 188, 129, -1));

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("11:30 AM");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 230, 96, 38));

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("03:00 PM");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 230, 96, 38));

        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("06:30 PM");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 230, 96, 38));

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("10:00 PM");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 230, 96, 38));

        inox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inox.setForeground(new java.awt.Color(255, 255, 255));
        inox.setText("INOX:SELVAM SQUARE,VELLORE.");
        jPanel1.add(inox, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 321, -1, 37));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("cancellation available");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 365, 129, 25));

        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("11:30 AM");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 418, 96, 38));

        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("03:00 PM");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 418, 96, 38));

        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("06:30 PM");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 418, 96, 38));

        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setText("10:00 PM");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 418, 96, 38));

        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setText("11:30 AM");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 569, 96, 38));

        jButton11.setForeground(new java.awt.Color(255, 0, 0));
        jButton11.setText("03:00 PM");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 569, 96, 38));

        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setText("06:30 PM");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 569, 96, 38));

        jButton13.setForeground(new java.awt.Color(255, 0, 0));
        jButton13.setText("10:00 PM");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 569, 96, 38));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 474, 205, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 482, 188, -1));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("cancellation available");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 524, -1, -1));

        cinepolis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinepolis.setForeground(new java.awt.Color(255, 255, 255));
        cinepolis.setText("CINEPOLIS,VELLORE.");
        jPanel1.add(cinepolis, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 489, 232, 28));

        movieName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 13, 161, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kaush\\Downloads\\movie time gif.gif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, 132));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/back button rezise.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 20, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("              ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 160, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\kaush\\Downloads\\logo white resize.jpg")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        datebox.setForeground(new java.awt.Color(255, 0, 0));
        datebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT DATE", "THU 17 NOV 2022", "FRI 18 NOV 2022", "SAT 19 NOV 2022", "SUN 20 NOV 2022", "MON 21 NOV 2022" }));
        datebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateboxActionPerformed(evt);
            }
        });
        jPanel1.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 71, 121, 37));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/pvr icon.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 40));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/inox icon.jpg"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, 40));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/Cinepolis icon.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=pvr.getText();
    String time=jButton5.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
  total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(pvr.getText());
ts.Time.setText(jButton5.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true); 
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=pvr.getText();
    String time=jButton4.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
  total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(pvr.getText());
ts.Time.setText(jButton4.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);  
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=inox.getText();
    String time=jButton8.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
   total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(inox.getText());
ts.Time.setText(jButton8.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);  
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=inox.getText();
    String time=jButton9.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
  total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(inox.getText());
ts.Time.setText(jButton9.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);   
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=inox.getText();
    String time=jButton6.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
  total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(inox.getText());
ts.Time.setText(jButton6.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);   
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=inox.getText();
    String time=jButton7.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(inox.getText());
ts.Time.setText(jButton7.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true); 
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=cinepolis.getText();
    String time=jButton10.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(cinepolis.getText());
ts.Time.setText(jButton10.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);     
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=cinepolis.getText();
    String time=jButton11.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(cinepolis.getText());
ts.Time.setText(jButton11.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);   
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
   if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=cinepolis.getText();
    String time=jButton12.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(cinepolis.getText());
ts.Time.setText(jButton12.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=cinepolis.getText();
    String time=jButton13.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(cinepolis.getText());
ts.Time.setText(jButton13.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);  
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=pvr.getText();
   String time=jButton2.getText();
   String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
//pst=con.prepareStatement("select * from moviefake where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(pvr.getText());
ts.Time.setText(jButton2.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true); 
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

if(datebox.getSelectedItem()=="SELECT DATE")
{
    invalidDate id=new invalidDate();
    id.setVisible(true);
}
else
{
    try
{
    String username=jLabel8.getText();
    String theatre=pvr.getText();
    String time=jButton3.getText();
    String selected=datebox.getSelectedItem().toString();
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set theatre='"+theatre+"',time='"+time+"',date='"+selected+"' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
total_seat ts=new total_seat();
String selected=datebox.getSelectedItem().toString();
ts.Date.setText(selected);
ts.Movie.setText(movieName.getText());
ts.Theatre.setText(pvr.getText());
ts.Time.setText(jButton3.getText());
ts.jLabel4.setText(jLabel8.getText());
ts.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
        choose_movie cm=new choose_movie();
        cm.jLabel4.setText(jLabel8.getText());
cm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateboxActionPerformed

    }//GEN-LAST:event_dateboxActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        setVisible(false);
        PVR P=new PVR();
        P.Movie.setText(movieName.getText());
        P.jLabel4.setText(jLabel8.getText());
        P.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        setVisible(false);
        INOX I=new INOX();
        I.Movie.setText(movieName.getText());
        I.jLabel4.setText(jLabel8.getText());
        I.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        setVisible(false);
        CINEPOLIS C=new CINEPOLIS();
        C.Movie.setText(movieName.getText());
        C.jLabel4.setText(jLabel8.getText());
        C.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_theatre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cinepolis;
    public javax.swing.JComboBox<String> datebox;
    public javax.swing.JLabel inox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel movieName;
    public javax.swing.JLabel pvr;
    // End of variables declaration//GEN-END:variables
}
