
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author nanim
 */
public class select_Seat extends javax.swing.JFrame {

    /**
     * Creates new form select_Seat
     */
    public select_Seat() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        seat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        movie = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        theatre = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox80 = new javax.swing.JCheckBox();
        jCheckBox81 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel7.setText("H");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel97.setText("jLabel97");

        jLabel98.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 0, 0));
        jLabel98.setText("               ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seat.setText("jLabel97");
        jPanel1.add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, -1, 39));

        date.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 127, 20));

        movie.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(movie, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 201, 27));

        time.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 61, 18));

        theatre.setText("jLabel97");
        jPanel1.add(theatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 37, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/back button rezise.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 24));

        user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 0, 0));
        user.setText("               ");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 150, 30));

        jLabel100.setIcon(new javax.swing.ImageIcon("C:\\Users\\kaush\\Downloads\\logo white resize.jpg")); // NOI18N
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox1.setText("D1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(23, 212, 43, 25);

        jCheckBox6.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox6.setText("H7");
        jPanel2.add(jCheckBox6);
        jCheckBox6.setBounds(429, 382, 43, 25);

        jCheckBox7.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox7.setText("H8");
        jPanel2.add(jCheckBox7);
        jCheckBox7.setBounds(490, 382, 43, 25);

        jCheckBox8.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox8.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox8.setText("H9");
        jPanel2.add(jCheckBox8);
        jCheckBox8.setBounds(551, 382, 43, 25);

        jCheckBox9.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox9.setText("A1");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox9);
        jCheckBox9.setBounds(23, 38, 43, 25);

        jCheckBox10.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox10.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox10.setText("B1");
        jPanel2.add(jCheckBox10);
        jCheckBox10.setBounds(23, 126, 43, 25);

        jCheckBox11.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox11.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox11.setText("C1");
        jPanel2.add(jCheckBox11);
        jCheckBox11.setBounds(23, 169, 43, 25);

        jCheckBox12.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox12.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox12.setText("E1");
        jPanel2.add(jCheckBox12);
        jCheckBox12.setBounds(23, 255, 43, 25);

        jCheckBox13.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox13.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox13.setText("F1");
        jPanel2.add(jCheckBox13);
        jCheckBox13.setBounds(23, 296, 43, 25);

        jCheckBox14.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox14.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox14.setText("G1");
        jPanel2.add(jCheckBox14);
        jCheckBox14.setBounds(23, 339, 43, 25);

        jCheckBox15.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox15.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox15.setText("H1");
        jPanel2.add(jCheckBox15);
        jCheckBox15.setBounds(23, 382, 43, 25);

        jCheckBox16.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox16.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox16.setText("A2");
        jPanel2.add(jCheckBox16);
        jCheckBox16.setBounds(92, 38, 43, 25);

        jCheckBox17.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox17.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox17.setText("B2");
        jPanel2.add(jCheckBox17);
        jCheckBox17.setBounds(92, 126, 43, 25);

        jCheckBox18.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox18.setText("E2");
        jPanel2.add(jCheckBox18);
        jCheckBox18.setBounds(92, 253, 43, 25);

        jCheckBox19.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox19.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox19.setText("C2");
        jPanel2.add(jCheckBox19);
        jCheckBox19.setBounds(92, 169, 43, 25);

        jCheckBox20.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox20.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox20.setText("F2");
        jPanel2.add(jCheckBox20);
        jCheckBox20.setBounds(92, 296, 43, 25);

        jCheckBox21.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox21.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox21.setText("G2");
        jPanel2.add(jCheckBox21);
        jCheckBox21.setBounds(92, 339, 43, 25);

        jCheckBox22.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox22.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox22.setText("H2");
        jPanel2.add(jCheckBox22);
        jCheckBox22.setBounds(92, 382, 43, 25);

        jCheckBox23.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox23.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox23.setText("A3");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox23);
        jCheckBox23.setBounds(162, 38, 43, 25);

        jCheckBox24.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox24.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox24.setText("B3");
        jPanel2.add(jCheckBox24);
        jCheckBox24.setBounds(162, 126, 43, 25);

        jCheckBox25.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox25.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox25.setText("C3");
        jPanel2.add(jCheckBox25);
        jCheckBox25.setBounds(162, 169, 43, 25);

        jCheckBox26.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox26.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox26.setText("E3");
        jPanel2.add(jCheckBox26);
        jCheckBox26.setBounds(162, 253, 43, 25);

        jCheckBox27.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox27.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox27.setText("F3");
        jPanel2.add(jCheckBox27);
        jCheckBox27.setBounds(162, 296, 43, 25);

        jCheckBox28.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox28.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox28.setText("G3");
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox28);
        jCheckBox28.setBounds(162, 339, 43, 25);

        jCheckBox29.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox29.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox29.setText("H3");
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox29ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox29);
        jCheckBox29.setBounds(162, 382, 43, 25);

        jCheckBox30.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox30.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox30.setText("A4");
        jPanel2.add(jCheckBox30);
        jCheckBox30.setBounds(223, 38, 43, 25);

        jCheckBox31.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox31.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox31.setText("B4");
        jPanel2.add(jCheckBox31);
        jCheckBox31.setBounds(223, 126, 43, 25);

        jCheckBox32.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox32.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox32.setText("C4");
        jPanel2.add(jCheckBox32);
        jCheckBox32.setBounds(223, 169, 43, 25);

        jCheckBox33.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox33.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox33.setText("E4");
        jPanel2.add(jCheckBox33);
        jCheckBox33.setBounds(223, 253, 43, 25);

        jCheckBox34.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox34.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox34.setText("F4");
        jPanel2.add(jCheckBox34);
        jCheckBox34.setBounds(223, 296, 43, 25);

        jCheckBox36.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox36.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox36.setText("H6");
        jPanel2.add(jCheckBox36);
        jCheckBox36.setBounds(368, 382, 43, 25);

        jCheckBox37.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox37.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox37.setText("A7");
        jCheckBox37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox37ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox37);
        jCheckBox37.setBounds(429, 38, 43, 25);

        jCheckBox38.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox38.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox38.setText("G6");
        jPanel2.add(jCheckBox38);
        jCheckBox38.setBounds(368, 339, 43, 25);

        jCheckBox39.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox39.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox39.setText("B6");
        jPanel2.add(jCheckBox39);
        jCheckBox39.setBounds(368, 126, 43, 25);

        jCheckBox40.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox40.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox40.setText("F6");
        jPanel2.add(jCheckBox40);
        jCheckBox40.setBounds(368, 296, 43, 25);

        jCheckBox41.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox41.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox41.setText("H5");
        jPanel2.add(jCheckBox41);
        jCheckBox41.setBounds(284, 382, 43, 25);

        jCheckBox42.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox42.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox42.setText("A6");
        jPanel2.add(jCheckBox42);
        jCheckBox42.setBounds(368, 38, 43, 25);

        jCheckBox43.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox43.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox43.setText("C6");
        jPanel2.add(jCheckBox43);
        jCheckBox43.setBounds(368, 169, 43, 25);

        jCheckBox44.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox44.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox44.setText("E6");
        jPanel2.add(jCheckBox44);
        jCheckBox44.setBounds(368, 253, 43, 25);

        jCheckBox45.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox45.setForeground(new java.awt.Color(255, 0, 51));
        jCheckBox45.setText("B5");
        jPanel2.add(jCheckBox45);
        jCheckBox45.setBounds(284, 126, 43, 25);

        jCheckBox46.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox46.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox46.setText("C5");
        jPanel2.add(jCheckBox46);
        jCheckBox46.setBounds(284, 169, 43, 25);

        jCheckBox47.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox47.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox47.setText("E5");
        jPanel2.add(jCheckBox47);
        jCheckBox47.setBounds(284, 253, 43, 25);

        jCheckBox48.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox48.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox48.setText("F5");
        jPanel2.add(jCheckBox48);
        jCheckBox48.setBounds(284, 296, 43, 25);

        jCheckBox49.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox49.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox49.setText("G5");
        jCheckBox49.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        jCheckBox49.setDoubleBuffered(true);
        jPanel2.add(jCheckBox49);
        jCheckBox49.setBounds(284, 339, 43, 25);

        jCheckBox50.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox50.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox50.setText("G4");
        jPanel2.add(jCheckBox50);
        jCheckBox50.setBounds(223, 339, 43, 25);

        jCheckBox51.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox51.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox51.setText("H4");
        jPanel2.add(jCheckBox51);
        jCheckBox51.setBounds(223, 382, 43, 25);

        jCheckBox52.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox52.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox52.setText("A5");
        jPanel2.add(jCheckBox52);
        jCheckBox52.setBounds(284, 38, 43, 25);

        jCheckBox57.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox57.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox57.setText("C9");
        jPanel2.add(jCheckBox57);
        jCheckBox57.setBounds(551, 169, 43, 25);

        jCheckBox58.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox58.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox58.setText("B9");
        jPanel2.add(jCheckBox58);
        jCheckBox58.setBounds(551, 126, 43, 25);

        jCheckBox60.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox60.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox60.setText("A9");
        jPanel2.add(jCheckBox60);
        jCheckBox60.setBounds(551, 38, 43, 25);

        jCheckBox61.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox61.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox61.setText("E9");
        jPanel2.add(jCheckBox61);
        jCheckBox61.setBounds(551, 253, 43, 25);

        jCheckBox62.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox62.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox62.setText("B8");
        jPanel2.add(jCheckBox62);
        jCheckBox62.setBounds(490, 126, 43, 25);

        jCheckBox65.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox65.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox65.setText("E9");
        jPanel2.add(jCheckBox65);
        jCheckBox65.setBounds(551, 296, 43, 25);

        jCheckBox66.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox66.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox66.setText("C8");
        jPanel2.add(jCheckBox66);
        jCheckBox66.setBounds(490, 169, 43, 25);

        jCheckBox67.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox67.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBox67.setText("E8");
        jPanel2.add(jCheckBox67);
        jCheckBox67.setBounds(490, 253, 43, 25);

        jCheckBox68.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox68.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox68.setText("F8");
        jCheckBox68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox68ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox68);
        jCheckBox68.setBounds(490, 296, 43, 25);

        jCheckBox69.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox69.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox69.setText("F7");
        jPanel2.add(jCheckBox69);
        jCheckBox69.setBounds(429, 296, 43, 25);

        jCheckBox71.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox71.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox71.setText("A8");
        jPanel2.add(jCheckBox71);
        jCheckBox71.setBounds(490, 38, 43, 25);

        jCheckBox72.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox72.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox72.setText("B7");
        jPanel2.add(jCheckBox72);
        jCheckBox72.setBounds(429, 126, 43, 25);

        jCheckBox73.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox73.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox73.setText("C7");
        jPanel2.add(jCheckBox73);
        jCheckBox73.setBounds(429, 169, 43, 25);

        jCheckBox74.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox74.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox74.setText("E7");
        jPanel2.add(jCheckBox74);
        jCheckBox74.setBounds(429, 253, 43, 25);

        jCheckBox54.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox54.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox54.setText("D2");
        jPanel2.add(jCheckBox54);
        jCheckBox54.setBounds(92, 212, 43, 25);

        jCheckBox55.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox55.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox55.setText("D3");
        jPanel2.add(jCheckBox55);
        jCheckBox55.setBounds(162, 212, 43, 25);

        jCheckBox56.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox56.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox56.setText("D8");
        jPanel2.add(jCheckBox56);
        jCheckBox56.setBounds(490, 212, 43, 25);

        jCheckBox59.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox59.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox59.setText("D4");
        jPanel2.add(jCheckBox59);
        jCheckBox59.setBounds(223, 212, 43, 25);

        jCheckBox75.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox75.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox75.setText("D5");
        jPanel2.add(jCheckBox75);
        jCheckBox75.setBounds(284, 212, 43, 25);

        jCheckBox76.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox76.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox76.setText("D6");
        jPanel2.add(jCheckBox76);
        jCheckBox76.setBounds(368, 212, 43, 25);

        jCheckBox77.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox77.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox77.setText("D7");
        jPanel2.add(jCheckBox77);
        jCheckBox77.setBounds(429, 212, 43, 25);

        jCheckBox78.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox78.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox78.setText("D9");
        jPanel2.add(jCheckBox78);
        jCheckBox78.setBounds(551, 212, 43, 25);

        jCheckBox79.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox79.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox79.setText("G7");
        jPanel2.add(jCheckBox79);
        jCheckBox79.setBounds(429, 339, 43, 25);

        jCheckBox80.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox80.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox80.setText("G8");
        jPanel2.add(jCheckBox80);
        jCheckBox80.setBounds(490, 339, 43, 25);

        jCheckBox81.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox81.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBox81.setText("G9");
        jPanel2.add(jCheckBox81);
        jCheckBox81.setBounds(551, 339, 43, 25);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 610, 420));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/screen this way.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 460, 100));

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Select Seats");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("selected seats are:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/booking/Picsart_22-11-16_20-10-08-692.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 310, 140));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 160, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
DefaultListModel model=new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String username=user.getText();
String row=jLabel2.getText();

//String s=jComboBox1.getSelectedItem().toString();
//String k=fromseat.getSelectedItem().toString();
//String l=toseat.getSelectedItem().toString();
//int a=Integer.parseInt(k);
//int b=Integer.parseInt(l);

    //obj.rows.setText(s+a+" to "+s+b);
//String row=jList1.getElement();
if(seat.getText()=="1")
{
    try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
PreparedStatement pst=con.prepareStatement("update moviefake set row='fgj',seat_number='dfhj' where username='"+username+"'");
                pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
   setVisible(false); 
priceCalculate obj=new priceCalculate();
    obj.Movie.setText(movie.getText());
obj.Date.setText(date.getText());
obj.Time.setText(time.getText());
obj.Seat.setText(seat.getText());
obj.rows.setText(jLabel2.getText());
obj.jLabel4.setText(user.getText());
obj.Theatre.setText(theatre.getText());
//obj.rows.setText(s+a);
obj.setVisible(true);
}
else
{
 try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
//PreparedStatement pst=con.prepareStatement("update moviefake set row='ljasjh',seat_number='kjsadjk to ljdf' where username='"+username+"'");
                //pst.executeUpdate();
}
catch(SQLException ex)
{
    Logger.getLogger(Newuser.class.getName()).log(Level.SEVERE,null,ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(choose_movie.class.getName()).log(Level.SEVERE, null, ex);
        }
 priceCalculate obj=new priceCalculate();
obj.Movie.setText(movie.getText());
obj.Date.setText(date.getText());
obj.Time.setText(time.getText());
obj.Seat.setText(seat.getText());
obj.jLabel4.setText(user.getText());
obj.rows.setText(jLabel2.getText());
obj.Theatre.setText(theatre.getText());
//obj.rows.setText(s+a+" to "+s+b);
obj.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
total_seat ts=new total_seat();
ts.Movie.setText(movie.getText());
ts.Date.setText(date.getText());
ts.Theatre.setText(theatre.getText());
ts.jLabel4.setText(user.getText());
ts.Time.setText(time.getText());
ts.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jCheckBox29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox29ActionPerformed

    private void jCheckBox37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox37ActionPerformed

    private void jCheckBox68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox68ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jCheckBox9.isSelected()){
         String lab=jLabel2.getText();
         String seat=jCheckBox9.getText();
         String username=user.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox9.setVisible(false);
                     }
        if(jCheckBox16.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox16.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox16.setVisible(false);// TODO add your handling code here:
    }
                    if(jCheckBox23.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox23.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox23.setVisible(false);// TODO add your handling code here:
    }
                     if(jCheckBox30.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox30.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox30.setVisible(false);
                     }
             if(jCheckBox52.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox52.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox52.setVisible(false);
                     }
              if(jCheckBox42.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox42.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox42.setVisible(false);
                     }
               if(jCheckBox37.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox37.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox37.setVisible(false);
                     }
                if(jCheckBox71.isSelected()){
         String lab=jLabel2.getText();
         String seat=jCheckBox71.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox71.setVisible(false);
                     }
                 if(jCheckBox60.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox60.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox60.setVisible(false);
                     }
                  if(jCheckBox10.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox10.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox10.setVisible(false);
                     }
                   if(jCheckBox17.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox17.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox17.setVisible(false);
                     }
                    if(jCheckBox24.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox24.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox24.setVisible(false);
                     }
                     if(jCheckBox31.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox31.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox31.setVisible(false);
                     }
                      if(jCheckBox45.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox45.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox45.setVisible(false);
                     }
                       if(jCheckBox39.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox39.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox39.setVisible(false);
                     }
                        if(jCheckBox72.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox72.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox72.setVisible(false);
                     }
                         if(jCheckBox62.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox62.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox62.setVisible(false);
                     }
                          if(jCheckBox58.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox58.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox58.setVisible(false);
                     }
                           if(jCheckBox11.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox11.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox11.setVisible(false);
                     }
                            if(jCheckBox19.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox19.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox19.setVisible(false);
                     }
                             if(jCheckBox25.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox25.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox25.setVisible(false);
                     }
                              if(jCheckBox32.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox32.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox32.setVisible(false);
                     }
                               if(jCheckBox46.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox46.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox46.setVisible(false);
                     }
                                if(jCheckBox43.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox43.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox43.setVisible(false);
                     }
                                 if(jCheckBox73.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox73.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox73.setVisible(false);
                     }
                                  if(jCheckBox66.isSelected()){
           String lab=jLabel2.getText();
         String seat=jCheckBox66.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox66.setVisible(false);
                     }
                                   if(jCheckBox57.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox57.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox57.setVisible(false);
                     }
                                    if(jCheckBox1.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox1.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox1.setVisible(false);
                     }
                                                                   if(jCheckBox54.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox54.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox54.setVisible(false);
                     }
                                                                                                  if(jCheckBox55.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox55.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox55.setVisible(false);
                     }
                                                                                                                                 if(jCheckBox59.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox59.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox59.setVisible(false);
                     }
                                                                                                                                                                if(jCheckBox75.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox75.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox75.setVisible(false);
                     }
        if(jCheckBox76.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox76.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox76.setVisible(false);
        }
        if(jCheckBox77.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox77.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox77.setVisible(false);
        }
                if(jCheckBox56.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox56.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox56.setVisible(false);
        }
                        if(jCheckBox78.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox78.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox78.setVisible(false);
        }
                                if(jCheckBox12.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox12.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox12.setVisible(false);
        }
                                 if(jCheckBox18.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox18.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox18.setVisible(false);
        }
                                  if(jCheckBox26.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox26.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox26.setVisible(false);
        }
          if(jCheckBox33.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox33.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox33.setVisible(false);
        }                         
         if(jCheckBox47.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox47.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox47.setVisible(false);
        }
          if(jCheckBox44.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox44.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox44.setVisible(false);
        }
           if(jCheckBox74.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox74.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox74.setVisible(false);
        }
          if(jCheckBox67.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox67.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox67.setVisible(false);
        }
           if(jCheckBox61.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox61.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox61.setVisible(false);
        }
            if(jCheckBox13.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox13.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox13.setVisible(false);
        }
             if(jCheckBox20.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox20.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox20.setVisible(false);
        }
              if(jCheckBox27.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox27.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox27.setVisible(false);
        }
               if(jCheckBox34.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox34.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox34.setVisible(false);
        }
          if(jCheckBox48.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox48.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox48.setVisible(false);
        }
           if(jCheckBox40.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox40.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox40.setVisible(false);
        }
            if(jCheckBox69.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox69.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox69.setVisible(false);
        }
             if(jCheckBox68.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox68.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox68.setVisible(false);
        }
              if(jCheckBox65.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox65.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox65.setVisible(false);
        }
               if(jCheckBox14.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox14.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox14.setVisible(false);
        }
               if (jCheckBox21.isSelected()) {
            String lab = jLabel2.getText();
            String seat = jCheckBox21.getText();
            jLabel2.setText(lab + seat + ",");
            jCheckBox21.setVisible(false);
        }
                if(jCheckBox28.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox28.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox28.setVisible(false);
        }
                 if(jCheckBox50.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox50.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox50.setVisible(false);
        }
                  if(jCheckBox49.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox49.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox49.setVisible(false);
        }
                   if(jCheckBox38.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox38.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox38.setVisible(false);
        }
                    if(jCheckBox79.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox79.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox79.setVisible(false);
        }
                     if(jCheckBox80.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox80.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox80.setVisible(false);
        }
                      if(jCheckBox81.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox81.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox81.setVisible(false);
        }
                       if(jCheckBox15.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox15.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox15.setVisible(false);
        }
                        if(jCheckBox22.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox22.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox22.setVisible(false);
        }
                         if(jCheckBox29.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox29.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox29.setVisible(false);
        }
                          if(jCheckBox51.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox51.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox51.setVisible(false);
        }
              if(jCheckBox41.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox41.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox41.setVisible(false);
        }
               if(jCheckBox36.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox36.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox36.setVisible(false);
        }
                if(jCheckBox6.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox6.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox6.setVisible(false);
        }
                 if(jCheckBox7.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox7.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox7.setVisible(false);
        }
                  if(jCheckBox8.isSelected()){
          String lab=jLabel2.getText();
         String seat=jCheckBox8.getText();
         jLabel2.setText(lab+seat+",");
           jCheckBox8.setVisible(false);
        }
                  jButton3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_Seat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox81;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel97;
    public javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel movie;
    public javax.swing.JLabel seat;
    public javax.swing.JLabel theatre;
    public javax.swing.JLabel time;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
